# Generated by Django 5.1.1 on 2024-10-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='image',
            field=models.ImageField(default='projects/default/project_d.png', upload_to='projects/subtask/'),
        ),
    ]
