# Generated by Django 5.1.1 on 2024-10-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_subtask_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AddField(
            model_name='subtask',
            name='project',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='image',
            field=models.ImageField(default='projects/default/project_d.png', upload_to='projects/task/'),
        ),
    ]
