# Generated by Django 5.1.1 on 2024-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='accounts/profile/default/default_avatar.jpg', upload_to='accounts/profile/'),
        ),
    ]
